/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Collection_detailCanisterIdRouteImport } from './routes/collection_detail/$canisterId'

const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Collection_detailCanisterIdRoute =
  Collection_detailCanisterIdRouteImport.update({
    id: '/collection_detail/$canisterId',
    path: '/collection_detail/$canisterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridge': typeof BridgeRoute
  '/collection_detail/$canisterId': typeof Collection_detailCanisterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridge': typeof BridgeRoute
  '/collection_detail/$canisterId': typeof Collection_detailCanisterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridge': typeof BridgeRoute
  '/collection_detail/$canisterId': typeof Collection_detailCanisterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/bridge' | '/collection_detail/$canisterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/bridge' | '/collection_detail/$canisterId'
  id: '__root__' | '/' | '/about' | '/bridge' | '/collection_detail/$canisterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BridgeRoute: typeof BridgeRoute
  Collection_detailCanisterIdRoute: typeof Collection_detailCanisterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection_detail/$canisterId': {
      id: '/collection_detail/$canisterId'
      path: '/collection_detail/$canisterId'
      fullPath: '/collection_detail/$canisterId'
      preLoaderRoute: typeof Collection_detailCanisterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BridgeRoute: BridgeRoute,
  Collection_detailCanisterIdRoute: Collection_detailCanisterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
